# This is a custom github action and accessing this from main workflow that is under .github/workflows
name: 'Setup Ansible'
description: 'Sets up Ansible for use in workflows'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
      shell: bash