name: python workflow 1

on:
  push:
    branches:
      - main
  workflow_dispatch:    # run enable run workflow button on github repository to trigger manually

jobs:
  pytest_job:
    runs-on: self-hosted
    # Whatever mentioned under steps will be performed sequentially
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'    # caching pip dependencies

      - name: run python command 
        run: python --version

      - name: install python required packages
        run: pip install -r requirements.txt

      - name: test python file 
        run: pytest -v
        continue-on-error: true

      - name: check hostname 
        run: hostname

  docker_build_job:
    runs-on: ubuntu-latest
    steps:
      - name: check hostname 
        run: hostname      

      - name: checkout repository     # Checkout into github repository
        uses: actions/checkout@v4        
        
      - name: setup docker      # setup docker environment
        uses: docker-practice/actions-setup-docker@master

      - name: run docker
        run: |
          set -x
          docker version
          docker build -t gjvignesh/pydockerimage .   

      - name: login into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}     # This will substitue secret variable value configured in github secrets and variables
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push docker image into docker hub
        run: docker push gjvignesh/pydockerimage

  ansible_install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository     # Checkout into github repository
        uses: actions/checkout@v4   

      - name: setup ansible
        uses: ./action_ansible_setup

      - name: "Print Ansible version"
        run: ansible --version      

  matrix_usage_job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}       # This variable will loop the values from strategy matrix
    steps:
      - name: checkout repository     # Checkout into github repository
        uses: actions/checkout@v4   

      - name: setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}    # This variable will loop the values from strategy matrix
          cache: 'pip'    # caching pip dependencies

      - name: run python command 
        run: python --version      
