name: python workflow 1

on:
  push:
    branches:
      - main
  workflow_dispatch:    # run enable run workflow button on github repository to trigger manually

jobs:
  python_job:
    runs-on: ubuntu-latest
    # Whatever mentioned under steps will be performed sequentially
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'    # caching pip dependencies

      - name: run python command 
        run: python --version

      - name: install python required packages
        run: pip install -r requirements.txt

      - name: check hostname 
        run: hostname

  pytest_job:
    runs-on: ubuntu-latest
    steps:
      - name: test 
        run: python --version

      - name: check hostname 
      run: hostname        


